### ISSUE TITLE
Changing the mode from draw_circle to simple_select on event onTouchEnd throws an error

### ISSUE THREAD

**Issue by pct-elizabeta-dimovska** [zakjan/mapbox-gl-draw-geodesic#28]
When the user draws a circle, after the shape is created the mode needs to be changed to simple select, but instead an error is thrown:

Console error
![console error](https://github.com/zakjan/mapbox-gl-draw-geodesic/assets/139766715/3caf1767-1a2b-4d3e-adf8-d3d4abc0f033)

The code is trying to access `Constants.modes.SIMPLE_SELECT`
![mouse up event](https://github.com/zakjan/mapbox-gl-draw-geodesic/assets/139766715/553f81ab-083b-4f76-a7ed-e628103fac92)

Constant `modes` doesn't contain property with key `SIMPLE_SELECT` - it's in lower case.
![constants](https://github.com/zakjan/mapbox-gl-draw-geodesic/assets/139766715/172e53c0-75f0-4601-86ca-d342eada2e53)

**Comment by zakjan** [comment]
Hi, this works for me in the [demo](https://zakjan.github.io/mapbox-gl-draw-geodesic/). Select `draw_circle` in the mode select, draw a circle, the mode switches back to simple_select.

Can you debug what's specific in your setup?

**Comment by jparish3** [comment]
your demo throws this error with any interaction after initial draw:get_features_and_set_cursor.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at N (get_features_and_set_cursor.js:14:18)
    at i.mouseup (events.js:63:20)
    at Ct.fire (evented.js:119:26)
    at i.fire (setup.js:53:24)
    at Oo.mouseup (map_event.js:38:19)
    at gr.handleEvent (handler_manager.js:325:58)

**Comment by Davey-Hughes** [comment]
Hi, I think I'm running into a similar issue. I've tried the demo as well in Chrome, Firefox, and Safari, and on Linux and MacOS. The demo for me shows non-geodesic lines whenever a mode that's not the draw_circle is selected:

<img width="1725" alt="image" src="https://github.com/zakjan/mapbox-gl-draw-geodesic/assets/9011230/465b55fb-8d88-482c-96ef-df2ed5a1a41c">

The object also has an extra field which is "undefined".

In this code: https://github.com/zakjan/mapbox-gl-draw-geodesic/blob/master/src/modes/index.js#L11-L22 what is happening when I step through the browser's debugger is `patchDrawLineString(modes[Constants.modes.DRAW_LINE_STRING])` calls the patch function with `undefined` presumably because Constants.modes.DRAW_LINE_STRING is undefined.

**Comment by zakjan** [comment]
Hi, the root cause was in incorrect reading existing mapbox-gl-draw modes after upgrading to mapbox-gl-draw 1.4.3. Fixed in https://github.com/zakjan/mapbox-gl-draw-geodesic/commit/f6ca244aa973160c69941ae4850e8d86771ec8d1 and released as 2.3.1. Could you try it?

**Comment by Davey-Hughes** [comment]
Hi this fix seems to work for me, thanks! I figured it was something better than my hardcoded solution but I'm not as familiar with the mapbox library.
